# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'
use_frameworks!

def shared_pods
   pod 'SwiftJWT'
end
 
target 'Example' do
   shared_pods
end

target 'ExampleTests' do
   shared_pods
end

target 'ExampleUITests' do
   shared_pods
end
